### ISSUE TITLE
Teams can be created with a space in there name, breaking commands

### ISSUE THREAD

**Issue by Feryc-Projects** [xF3d33/UltimateTeams#13]
players can create team names such as "team team"

but these names do not get respected by the Ultimate Teams like when disbanding the team by
teamadmin disband team team
[12:54:46 INFO]: Could not find player team. They may be have not joined before.

**Comment by xF3d33** [comment]
Hello, thanks for your report. so, I have to make so the plugin doesn't let you create a team with a space? also, are you using mysql or sqlite?

**Comment by Feryc-Projects** [comment]
plugin: Ultimate Teams 2.0.4 (standard no custom changes)
server core: git-Paper-196 (MC: 1.20.1)
sqlite brand new map (no config changes)

[13:43:25 INFO]: Feryc issued server command: /team create test test
[13:43:25 INFO]: [UltimateTeams] Attempting to connect to database
[13:43:25 INFO]: [UltimateTeams] SQLite Database Connected!
![image](https://github.com/xF3d33/UltimateTeams/assets/105493615/a3f071c9-27a6-4ce2-87d1-869cbb97def6)

**Comment by xF3d33** [comment]
this should be fixed with the new version (2.1). if not, please let me know.
