### ISSUE TITLE
/team leave, Not saving changes.

### ISSUE THREAD

**Issue by Feryc-Projects** [xF3d33/UltimateTeams#14]
When a player uses /team leave they will successfully have left the team, but after a server restart they are back in the team they left

**Comment by xF3d33** [comment]
Hello, do you see any error in the console when the player uses the command or at startup? are you using mysql or sqlite

**Comment by Feryc-Projects** [comment]
Well there's no errors,
And it's with mysql lite and mysql.

Am i correct it's because the teamLeaveSubCommand class is missing plugin.runAsync(() -> plugin.getDatabase().updateTeam(team));

**Comment by xF3d33** [comment]
yes if it is missing in the class and in the handler you are correct. I'm currently working on a new branch, but I'll check and push an update for this
