### ISSUE TITLE
Team issue

### ISSUE THREAD

**Issue by michadasis** [xF3d33/UltimateTeams#23]
Some player created a team named Ball of flame no underscores no nothing & now people can't ally with them, any way to run the command since I can't even disband their team either

**Comment by xF3d33** [comment]
So they created a team with a name that contains a space?
Can you please send me an output of /team list?

Also, which version of the plugin are you using and what storage method?

**Comment by xF3d33** [comment]
So, with a3e64ca6f1b38676b0eaaf5e797cc203f0fa7aa8 i added a dedicated check for space in team names, so this should definitely fix your issue. 

but i still think you are in a past version, as 2.1 already fixed it. let me know if you are still encountering any issue.
Be sure to update to version 2.2

**Comment by michadasis** [comment]
Okay, thanks.
