### ISSUE TITLE
[Feature Request] Integrate with CarbonChat

### ISSUE THREAD

**Issue by NyaomiDEV** [xF3d33/UltimateTeams#25]
Some servers already use CarbonChat to manage chat channels, which also are cross-server if set up correctly (plugging in #9). It would be nice if team/ally/other chats can be integrated with Carbon, to have a single comprehensive chat experience.

**Comment by xF3d33** [comment]
i checked the plugin repo, but i didn't find an api guide, and the plugin didn't seem finished.
I am not sure if i will add an hook for it (it's not very simple actually). 

probably in the near future i will add support for
https://github.com/Rosewood-Development/RoseChat
which is a fantastic plugin for me. But feel free to add it yourself and create a pull request
