### ISSUE TITLE
[BUG] teamName PAPI placeholder adds a space as last character

### ISSUE THREAD

**Issue by NyaomiDEV** [xF3d33/UltimateTeams#26]
Right now it's impossible to use the team name on holograms without it adding a space.

Formatting `Hi %player_displayname%, your team is %ultimateteams_teamName%.` adds a space before the last dot and it becomes `Hi Joe, your team is Knights .`

**Comment by xF3d33** [comment]
Hey, I will fix this today, then if you want I can provide you a fixed build before pushing an update on modrinth

**Comment by xF3d33** [comment]
If you want the fixed build immediately, you can contact me on discord (xF3d3) or you can build it yourself
