### ISSUE TITLE
[Feature Request] Auto invite wipe task verbosity

### ISSUE THREAD

**Issue by NyaomiDEV** [xF3d33/UltimateTeams#27]
[This line](https://github.com/xF3d33/UltimateTeams/blob/8b94b0f57463abdb71e57f31803b45cba34160be/src/main/java/dev/xf3d3/ultimateteams/UltimateTeams.java#L224) could use another check to see if we want this logged at all (of course if there's an error that has to be logged regardless)

**Comment by xF3d33** [comment]
So what solution would you propose?

**Comment by NyaomiDEV** [comment]
> So what solution would you propose?

Something like this in the config file

```yml
# Do you want the console to log when invites get wiped? [Default value: true]
auto-invite-wipe-task-verbose: true
```
