### ISSUE TITLE
[Feature Request] Add rank/role function, add set permissions to limit members (or you can make upgrade menu with /team upgrade command

### ISSUE THREAD

**Issue by AquaMCVN** [xF3d33/UltimateTeams#28]
**Add rank/role function**
add management level/role (have all rights in the group) can set maximum number of people as managers in config settings and adjust prefix there eg: Manager, admin , etc

**add set permissions to limit setwarps, members**
quite useful i can make a menu for members to upgrade the maximum number of members, the number of warps set, like above you can make a hook menu with vaults or playerpoints etc

**Comment by AquaMCVN** [comment]
> Hey, can you edit this issue and create single ones for each request?

ok i will

**Comment by xF3d33** [comment]
i added warps limit with permission, check #29. i haven't tested it yet. if you want contact me on discord (xF3d3) and i can send you the new version immediately

**Comment by xF3d33** [comment]
please modify your issue as requested
