### ISSUE TITLE
Fix error

### ISSUE THREAD

**Issue by TATA82** [xF3d33/UltimateTeams#3]
![image](https://github.com/xF3d33/UltimateTeams/assets/42910508/8b6dbad9-da1f-40f9-aabb-8cd76e126d42)
![image](https://github.com/xF3d33/UltimateTeams/assets/42910508/10216fb6-f0d6-4f40-8b83-bd9e17fdbe10)

**Comment by xF3d33** [comment]
Hello, can you tell me which command causes that error?

**Comment by TATA82** [comment]
![image](https://github.com/xF3d33/UltimateTeams/assets/42910508/93cd2be2-e21a-463c-a3ee-c9aa5ff4e036)

**Comment by xF3d33** [comment]
> ![image](https://user-images.githubusercontent.com/42910508/260008989-8657f714-11f7-4dd7-88ce-2cba148ee3c4.png)

Hey there, so i fixed the error related to this command, but i can't replicate the one from the other command... can you send me your messages file?

**Comment by xF3d33** [comment]
closed due to inactivity
