### ISSUE TITLE
[Feature Request] Configurable messages for blank placeholders

### ISSUE THREAD

**Issue by Kruseified** [xF3d33/UltimateTeams#35]
Would be a great addition to have a configurable message for %ultimateteams_teamName% placeholder when the user is not currently in a team.

Most of the time networks like to keep team name within their scoreboard, when no team is joined, it looks a bit odd having a large blank area.

I have attached a photo for example.

![image](https://github.com/user-attachments/assets/b3b4b789-04a9-4c66-8302-3cb5aa338f6f)

**Comment by xF3d33** [comment]
can you try the latest build and check if it works correctly?
