### ISSUE TITLE
Error sending invitation to team

### ISSUE THREAD

**Issue by Lollo-00** [xF3d33/UltimateTeams#4]
When any player makes the invitation command for his team to another player does not and in console from this error:
![image](https://github.com/xF3d33/UltimateTeams/assets/79920115/bc1e3762-6f43-42ec-8726-5583cdd31045)

**Comment by xF3d33** [comment]
hello, sorry for the delay, do you have floodgate correctly installed with his api enabled?

**Comment by Lollo-00** [comment]
No problem, yes i have correctly installed floodgate. The problem happens when I activate "floodgate-hook: false"

**Comment by xF3d33** [comment]
> No problem, yes i have correctly installed floodgate. The problem happens when I activate "floodgate-hook: false"

i tried to replicate the error multiple times but i can invite any other player without any problem. are you sure your setup is correct? which server version are you using?

**Comment by Lollo-00** [comment]
the server version (backend) is the paper "Paper-1.20.1-171", instead as proxy use "flamecord latest version". I also attach that of floodgates and geysers "#69" & "#299"

**Comment by Lollo-00** [comment]
> > No problem, yes i have correctly installed floodgate. The problem happens when I activate "floodgate-hook: false"
> 
> i tried to replicate the error multiple times but i can invite any other player without any problem. are you sure your setup is correct? which server version are you using?

the server version (backend) is the paper "Paper-1.20.1-171", instead as proxy use "flamecord latest version". I also attach that of floodgates and geysers "#69" & "#299"

**Comment by xF3d33** [comment]
ok so you need geyser only in the proxy server with a key.pem file generated from floodgate and auth type floodgate, then floodgate both in backend and proxy

 you have to copy the same .pem file in all servers with floodgate, both proxy and backend, and in the proxy server enable the api in the floodgate config.

if after a restart you still have the issue contact me on discord @xF3d3
