### ISSUE TITLE
[QUESTION] how to add another colums in the plugin's database

### ISSUE THREAD

**Issue by kosmakotek09** [xF3d33/UltimateTeams#40]
How casn i add addional columns in my mysql database?

Hi, my question is how can i add other columns such as player_team in ultimateteams_users table or player deathcount or players_in/-team column in ultimateteams_teams table
![Zrzut ekranu 2024-10-15 203123](https://github.com/user-attachments/assets/f3effdad-960b-45ef-8f0c-beb5e063f8aa)
?

i'll be thankful for help.

**Comment by xF3d33** [comment]
Hi, can you explain me what your're trying to achieve?

**Comment by kosmakotek09** [comment]
> Hi, can you explain me what your're trying to achieve?
 I am trying to get which team player is in, on my table on sql. Like how to catch another data to colums from game?

**Comment by xF3d33** [comment]
if you want to get the player's team within the game you can just parse the placeholder

**Comment by xF3d33** [comment]
write me on Discord so i can try to help you. xF3d3 is the name

**Comment by xF3d33** [comment]
write me on Discord so i can try to help you. xF3d3 is the name
