### ISSUE TITLE
Sync accross servers with MYSQL database

### ISSUE THREAD

**Issue by JorisvD01** [xF3d33/UltimateTeams#6]
I have the plugin setup in different servers using the same MYSQL database, but whenever I create a team in one server, it doesnt automatically update in the others. Only after a restart it updates in those servers

**Comment by xF3d33** [comment]
yeah, it is not a multiserver compatible plugin. it's not simple to make it compatible, and right now I'm not planning to do so, since it would require a long rewrite of almost everything..

**Comment by JorisvD01** [comment]
Alright! Thanks for the info

**Comment by xF3d33** [comment]
Hi! I actually added support for cross server now with v4.x, if you still need it
